tasks:
  - name: Backend
    before: npm install
    command: npm run dev
  - name: Frontend
    before: |
      cd frontend
      npm install
    command: npm run dev

ports:
  - port: 3001 # Backend
    onOpen: ignore
  - port: 5173 # Frontend (el puerto por defecto de Vite)
    onOpen: open-preview
